#### Import libraries:

In [2]:
import os
import cv2
import random
from random import shuffle, sample
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

# from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img

### De opdracht 


Er zijn meerdere methoden voor het beoordelen van een appel batch. Voor dit project vragen we jullie om een implementatie te maken van het zogenaamde Acceptance Quality Limit (AQL) protocol. Dit protocol is een industriestandaard voor statistische kwaliteitscontroles. Informatie hierover vinden jullie in de projectbijlages (aql_poster.pdf). 

We hanteren de volgende kwaliteitslabels: 

Klasse 1: kwaliteit appels is goed genoeg om in supermarkt of bij groenteboer​ te liggen 
Klasse 2: kwaliteit appels is goed genoeg voor verwerking in appelmoes 
Klasse 3: kwaliteit appels is goed genoeg voor verwerking in stroop 
Afgekeurd: kwaliteit is onvoldoende voor bovenstaande toepassingen 

Schrijf ook een compact programma dat op basis van de validatie- en test-set van de appels een batch samenstelt, waarop je een inspectie kunt uitvoeren. Hieruit moet dan het juiste kwaliteitslabel rollen. 


### 1. Inladen van het model en de data

In [3]:
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.keras.utils import load_img, img_to_array 
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

mobileNetV2 = load_model('../models/mobileNetV2_256px.h5')

model = load_model('../models/cleanedAndAugumented_470images_M3_256px.h5')

dirBatch01 = '../data/batches/batch01/'
dirBatch02 = '../data/batches/batch02/'
dirBatch03 = '../data/batches/batch03/'

batches = [dirBatch01, dirBatch02, dirBatch03]

txtFiles = list()
foto_path = list()

predBatches=[[],[],[]]

tel=0

for i in batches:
  txtFile = os.path.join(i)
  txtFiles.append(txtFile) 
  foto_path.append(os.listdir(i))

  for filename in os.listdir(i):
    txtFile = os.path.join(i, filename)
    x = img_to_array(Image.open(txtFile)).astype('uint8')
    y = np.stack([x], axis=0)
    print(x)
    
    predictions=mobileNetV2.predict([y])
    appletypenr = np.argmax(predictions)
    predBatches[tel].append(appletypenr)
  tel+=1
  
print(predBatches)


2022-12-05 12:29:05.944509: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
1/1 [==============================] - 1s 1s/step
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [

In [4]:
predBatch01 = (predBatches[0])
print(predBatch01)
  
predBatch02 = (predBatches[1])
print(predBatch02)

predBatch03 = (predBatches[2])
print(predBatch03)

[2, 2, 3, 2, 0, 0, 0, 1, 3, 2, 0, 0, 1, 3, 0, 2, 3, 2, 1, 1, 1, 0, 3, 1, 1, 0, 0, 0, 1, 1, 2, 2, 1, 3, 3, 0, 2, 3, 0, 1, 3, 1, 3, 3, 0, 0, 0, 3, 1, 3, 0, 1, 0, 0, 2, 1, 3, 2, 2, 2, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 1, 3]
[0, 2, 2, 2, 2, 2, 2, 1, 0, 0, 2, 2, 2, 3, 2, 3, 0, 2, 2, 2, 2, 2, 0, 0, 3, 3, 2, 2, 2, 3, 0, 1, 2, 2, 1, 2, 0, 3, 1, 2, 0, 2, 3, 2, 0, 3, 1, 3, 3, 0, 2, 0, 3, 1, 0, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 3, 1, 1, 0, 0, 0, 0, 1, 3, 0, 2, 2, 0, 3, 0]
[2, 1, 2, 2, 2, 2, 0, 0, 2, 3, 0, 0, 1, 2, 1, 1, 3, 2, 0, 0, 2, 1, 2, 1, 0, 0, 3, 2, 2, 1, 3, 0, 3, 0, 2, 1, 0, 2, 0, 3, 2, 3, 0, 1, 3, 3, 0, 2, 3, 2, 1, 0, 0, 0, 2, 3, 1, 2, 0, 3, 1, 0, 0, 2, 2, 1, 1, 1, 3, 1, 2, 3, 0, 1, 2, 2, 2, 2, 2, 3]


In [5]:
# batch01Blotch = (predBatch01[0])
# batch01Normal = (predBatch01[1])
# batch01Rot = (predBatch01[2])
# batch01Scab = (predBatch01[3])